version: '3.8'

networks:
  bayan:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: kx-nginx
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - bayan
    volumes:
      - ./backend:/app
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx

  postgres:
    image: postgres:14-alpine3.15
    container_name: kx-postgres
    hostname: kx-postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: db
      DB_DATABASE_TESTING: db-test
    volumes:
      - ./docker/postgres/pg-data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    networks:
      - bayan

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kx-php
    environment:
        DATABASE_URL: postgresql://postgres:secret@postgres:5432/db
        DB_HOST: postgres
        DB_PORT: 5432
        DB_DATABASE: db
        DB_USERNAME: postgres
        DB_PASSWORD: secret
        DB_DATABASE_TESTING: db-test
        TELGRAM_BOT_TOKEN: 1234567890:ABCDEF
        TELEGRAM_APP_URL: https://api.telegram.org/bot+${TELGRAM_BOT_TOKEN}
#    command: tail -f /dev/null
    ports:
      - 5173:5173
    volumes:
      - ./docker/config/php.conf.ini:/usr/local/etc/php/conf.d/php.ini
      - ./backend:/app
    networks:
      - bayan

volumes:
  pg-data:
    driver: local

